#!/bin/sh

set -xe
# See http://www.wtfpl.net/txt/copying for license details
# Creates a minimal manifest and manifest.uuid file so sqlite (and fossil) can build
git rev-parse --git-dir >/dev/null || exit 1
echo $(git log -1 --format=format:%H) > manifest.uuid.tmp
echo C $(cat manifest.uuid.tmp) > manifest.tmp
git log -1 --format=format:%ci%n | sed 's/ [-+].*$//;s/ /T/;s/^/D /' >> manifest.tmp
# Avoid updating the manifest files if nothing changed:
cmp --quiet manifest.uuid manifest.uuid.tmp || cp -f manifest.uuid.tmp manifest.uuid
rm -f manifest.uuid.tmp
cmp --quiet manifest manifest.tmp || cp -f manifest.tmp manifest
rm -f manifest.tmp

